# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gTzYoKarGFdSMmZ9FryO0dw8u8tTso2A
"""

import random
import pandas as pd
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data

df = pd.DataFrame({
    "human": ["human" in item for item in lst],
    "robot": ["robot" in item for item in lst]
})
df

pd.get_dummies(data['whoAmI'])